#**[Problem 1]**
##***Matrix product is calculated manually***

<p>The 3 by 3 matrices can be multiplied in the following way.</p>
<p>First, we express the two matrices, $A$ and $B$.</p>

$$A=
 \left[
 \begin{matrix}
   -1 & 2 & 3 \\
   4 & -5 & 6 \\
   7 & 8 & -9
  \end{matrix}
  \right],
  B=
  \left[
    \begin{matrix}
   0 & 2 & 1 \\
   0 & 2 & -8 \\
   2 & 9 & -1
  \end{matrix}
  \right]
$$

<p>The product of two matrices are obtained by multiplying each row by each column. To get the value of $a_{0, 0}$, the first row in matrix $A$ shall be multiplied by the first column in matrix $B$ and the products added. To get $a_{0,1}$, the first row in $A$ will be multiplied with the second column in $B$, and then the products  added. the process is repeated for each position until the resulting matrix is completed.</p>



<p>The calculation of the the product of the matrices $A$ and $B$ is given below:</p>

$$C=A \times B=
 \left[
 \begin{matrix}
   -1 & 2 & 3 \\
   4 & -5 & 6 \\
   7 & 8 & -9
  \end{matrix}
  \right]
  \times
  \left[
    \begin{matrix}
   0 & 2 & 1 \\
   0 & 2 & -8 \\
   2 & 9 & -1
  \end{matrix}
  \right]
$$

<p>The rows are multiplied with the columns in the following way:</p>

$$C=
 \left[
 \begin{matrix}
   (-1\times 0)+(2\times 0)+(3\times 2) & (-1\times 2)+(2\times 2)+(3\times 9) & (-1\times 1)+(2\times -8)+(3\times -1) \\
   (4\times 0)+(-5\times 0)+(6\times 2) & (4\times 2)+(-5\times 2)+(6\times 9) & (4\times 1)+(-5\times -8)+(6\times -1)\\
   (7\times 0)+(8\times 0)+(-9\times 2) & (7\times 2)+(8\times 2)+(-9\times 9) & (7\times 1)+(8\times -8)+(-9\times -1)
  \end{matrix}
  \right]
$$

<p>Tthe products of the rows and columns are then added in each position</p>

$$C=
 \left[
 \begin{matrix}
   0+0+6 & (-2)+4+27 & (-1)+(-16)+(-3) \\
   0+0+12 & 8+(-10)+54 & 4+40+(-6)\\
   0+0+(-18) & 14+16+(-81) & 7+(-64)+9
  \end{matrix}
  \right]
$$

<p> The Answer is:

$$C=
 \left[
 \begin{matrix}
   6 & 29 & -20 \\
   12 & 52 & 38\\
   -18 & -51 & -48
  \end{matrix}
  \right]
$$

#**[Problem 2]**
##***Calculation by NumPy function***

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

###*Using np.matmul()*

In [2]:
c_ndarray_1 = np.matmul(a_ndarray, b_ndarray)
print(c_ndarray_1)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


###*Using @ operator*

In [3]:
c_ndarray_2 = a_ndarray @ b_ndarray
print(c_ndarray_2)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


###*Using np.dot()*

In [4]:
c_ndarray_3 = np.dot(a_ndarray, b_ndarray)
print(c_ndarray_3)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


#**[Problem 3]**
##***Implementation of calculation of a certain element*** 

In [5]:
c_ndarray_5 = np.array([[0,0,0],
         [0,0,0],
         [0,0,0]])

# iterate through rows of X
for i in range(len(a_ndarray)):
   # iterate through columns of Y
   for j in range(len(b_ndarray[0])):
       # iterate through rows of Y
       for k in range(len(b_ndarray)):
           c_ndarray_5[i][j] += a_ndarray[i][k] * b_ndarray[k][j]


print(c_ndarray_5)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


#**[Problem 4]**
##***Creating a function that performs matrix multiplication***

In [6]:
# Create a function that can multiply matrices
def matrix_multiplier(a,b):
  import numpy as np
  c_ndarray_6 = np.array([[0 for x in range(len(b[0]))] for y in range(len(a))])
  # iterate through rows of a
  for i in range(len(a)):
    # iterate through columns of b
    for j in range(len(b[0])):
      # iterate through rows of b
      for k in range(len(b)):
        c_ndarray_6[i][j] += a[i][k] * b[k][j]
  return c_ndarray_6

matrix_multiplier(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

#**[Problem 5]**
##***Judge the input whose calculation is not defined***

In [7]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# Create a function that can multiply matrices and judges if calculation is not defined
def matrix_multiplier2(a,b):
  import numpy as np
  c_ndarray_7 = np.array([[0 for x in range(len(b[0]))] for y in range(len(a))])
  # iterate through rows of a
  for i in range(len(a)):
    # iterate through columns of b
    for j in range(len(b[0])):
      # iterate through rows of b
      for k in range(len(b)):
        c_ndarray_7[i][j] += a[i][k] * b[k][j]
  # for metrix multiplication to be defined, the number of columns in a must be equal to the number of rows in b, therefore:
  if len(a[0]) != len(b):
    print("Matrix multiplication is not defined")
  else:
    print(np.array(c_ndarray_7))

matrix_multiplier2(d_ndarray,e_ndarray)

Matrix multiplication is not defined


#**[Problem 6]**
##Transposition**

###*Using np.transpose()*

In [8]:
# Transpose e_ndarray to make multiplication of matrices possible

import numpy as np

e_ndarray2 = np.transpose(e_ndarray)
print(e_ndarray2)

[[-9  6]
 [ 8 -5]
 [ 7  4]]


In [9]:
# Perform multiplication
matrix_multiplier2(d_ndarray,e_ndarray2)

[[ 46  -4]
 [-34  73]]


###Using np.ndarray.T

In [10]:
# Transpose e_ndarray to make multiplication of matrices possible

import numpy as np

e_ndarray3 = e_ndarray.T
print(e_ndarray2)

[[-9  6]
 [ 8 -5]
 [ 7  4]]


In [11]:
# Perform multiplication
matrix_multiplier2(d_ndarray,e_ndarray3)

[[ 46  -4]
 [-34  73]]
